apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-pv
  name: nginx-pv-service
spec:
  type: NodePort
  ports:
    - port: 9095
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-pv
  name: nginx-pv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pv
  template:
    metadata:
      labels:
        app: nginx-pv
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - image: nginx
          name: nginx-pv
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: task-pv-storage
