apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-for-k8s
  name: spring-boot-service
spec:
  type: NodePort
  ports:
  - port: 9095
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-for-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-for-k8s
  name: spring-boot-for-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-for-k8s
  template:
    metadata:
      labels:
        app: spring-boot-for-k8s
    spec:
      containers:
      - image: localhost:32000/spring-boot:latest
        name: spring-boot
        ports:
        - containerPort: 8080
